#!/usr/bin/env python3
"""Turn gpu_screen.ptx into gpu_ptx.h, a C string literal array.

The PTX is embedded in the executable so that BigCalcGMP stays a single
MinGW-built binary with no CUDA runtime dependency: at run time it is handed
to cuModuleLoadDataEx(), which JITs it for whatever GPU is present.

Usage: python ptx_to_header.py <input.ptx> <output.h>
"""
import sys

def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, "r", encoding="utf-8", errors="replace") as fh:
        ptx = fh.read()
    # PTX is ASCII; escape defensively anyway.
    body = ptx.replace("\\", "\\\\").replace('"', '\\"')
    lines = body.split("\n")
    out = []
    out.append("// Generated by ptx_to_header.py from gpu_screen.cu -- do not edit.")
    out.append("// Regenerate with: nvcc -ptx -arch=compute_120 -O3 gpu_screen.cu && python ptx_to_header.py ...")
    out.append("#pragma once")
    out.append("static const char GPU_PTX_SOURCE[] =")
    for ln in lines:
        out.append('    "%s\\n"' % ln)
    out.append("    ;")
    out.append("static const unsigned long long GPU_PTX_LEN = %dULL;" % len(ptx))
    with open(dst, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out) + "\n")
    print("wrote %s (%d bytes of PTX, %d lines)" % (dst, len(ptx), len(lines)))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
